/**
 * For bottom container menu
 * menuText;
 * menuTextColor;
 * menuLinkType;
 * menuInternalLinkUrl;
 * menuExternalLinkUrl;
 * icon;
 */
class HomeModel {
    homePageDisplayRibbon;
    homePageRibbonPosition;
    homePageRibbonText;
    homePageRibbonTextColor;
    homePageRibbonBackgroundColor;
    homePageRibbonLinkType;
    homePageRibbonLink;
    homePageRibbonLinkInternal;
    homePageRibbonLinkExternal
    homePageRibbonDisplayIcon;
    homePageRibbonIcon;
    homePageRibbonIconPosition;
    HomePageRibbonTextMarquee;
    homePageTopBackgroundImage;
    homePageTopBackgroundGradientStartColor;
    homePageTopBackgroundGradientStopColor;
    homePageTopBackgroundOpacity;
    homePageTopTextLine1;
    homePageTopTextLine1Color;
    homePageTopTextUnderLine1;
    homePageTopTextUnderLine1Color;
    homePageTopTextLine2;
    homePageTopTextLine2Color;
    homePageTopTextUnderLine2;
    homePageTopTextUnderLine2Color;
    homePageDisplayTopButton;
    homePageTopButtonText;
    homePageTopButtonTextColor;
    homePageTopButtonGradientStartColor;
    homePageTopButtonGradientStopColor;
    homePageTopButtonLinkType;
    homePageTopButtonLink;
    homePageTopButtonLinkInternal;
    homePageTopButtonLinkExternal;
    homePageBottomBackgroundImage;
    homePageBottomBackgroundGradientStartColor;
    homePageBottomBackgroundGradientStopColor;
    homePageBottomBackgroundOpacity;
    homePageBottomDisplayIcon;
    homePageBottomDisplayArrowIcon;
    homePageBottomArrowColor;
    homePageBottomTextAlign;
    homePageDisplayFooter;
    homePageBottomIconShape;
    homePageBottomIconColor;
    homePageBottomIconBackgroundColor;
    footerLinks;
    menuLinks;
    constructor() { }
    setHomeScreenData(data) {
        this.homePageDisplayRibbon = data.homePageDisplayRibbon;
        this.homePageRibbonPosition = data.homePageRibbonPosition;
        this.homePageRibbonText = data.homePageRibbonText;
        this.homePageRibbonTextColor = data.homePageRibbonTextColor;
        this.homePageRibbonBackgroundColor = data.homePageRibbonBackgroundColor;
        this.homePageRibbonLinkType = data.homePageRibbonLinkType;
        this.homePageRibbonLink = data.homePageRibbonLink;
        this.homePageRibbonLinkInternal = data.homePageRibbonLinkInternal;
        this.homePageRibbonLinkExternal = data.homePageRibbonLinkExternal;
        this.homePageRibbonDisplayIcon = data.homePageRibbonDisplayIcon;
        this.homePageRibbonIcon = data.homePageRibbonIcon;
        this.homePageRibbonIconPosition = data.homePageRibbonIconPosition;
        this.homePageRibbonTextMarquee = data.homePageRibbonTextMarquee;
        this.homePageTopBackgroundImage = data.homePageTopBackgroundImage;
        this.homePageTopBackgroundGradientStartColor = data.homePageTopBackgroundGradientStartColor;
        this.homePageTopBackgroundGradientStopColor = data.homePageTopBackgroundGradientStopColor;
        this.homePageTopBackgroundOpacity = data.homePageTopBackgroundOpacity;
        this.homePageTopTextLine1 = data.homePageTopTextLine1;
        this.homePageTopTextLine1Color = data.homePageTopTextLine1Color;
        this.homePageTopTextUnderLine1 = data.homePageTopTextUnderLine1;
        this.homePageTopTextUnderLine1Color = data.homePageTopTextUnderLine1Color;
        this.homePageTopTextLine2 = data.homePageTopTextLine2;
        this.homePageTopTextLine2Color = data.homePageTopTextLine2Color;
        this.homePageTopTextUnderLine2 = data.homePageTopTextUnderLine2;
        this.homePageTopTextUnderLine2Color = data.homePageTopTextUnderLine2Color;
        this.homePageDisplayTopButton = data.homePageDisplayTopButton;
        this.homePageTopButtonText = data.homePageTopButtonText;
        this.homePageTopButtonTextColor = data.homePageTopButtonTextColor;
        this.homePageTopButtonGradientStartColor = data.homePageTopButtonGradientStartColor;
        this.homePageTopButtonGradientStopColor = data.homePageTopButtonGradientStopColor;
        this.homePageTopButtonLinkType = data.homePageTopButtonLinkType;
        this.homePageTopButtonLink = data.homePageTopButtonLink;
        this.homePageTopButtonLinkInternal = data.homePageTopButtonLinkInternal;
        this.homePageTopButtonLinkExternal = data.homePageTopButtonLinkExternal;
        this.homePageBottomBackgroundImage = data.homePageBottomBackgroundImage;
        this.homePageBottomBackgroundGradientStartColor = data.homePageBottomBackgroundGradientStartColor;
        this.homePageBottomBackgroundGradientStopColor = data.homePageBottomBackgroundGradientStopColor;
        this.homePageBottomBackgroundOpacity = data.homePageBottomBackgroundOpacity;
        this.homePageBottomDisplayIcon = data.homePageBottomDisplayIcon;
        this.homePageBottomDisplayArrowIcon = data.homePageBottomDisplayArrowIcon;
        this.homePageBottomArrowColor = data.homePageBottomArrowColor;
        this.homePageBottomTextAlign = data.homePageBottomTextAlign;
        this.homePageDisplayFooter = data.homePageDisplayFooter;
        this.homePageBottomIconShape = data.homePageBottomIconShape;
        this.homePageBottomIconColor = data.homePageBottomIconColor;
        this.homePageBottomIconBackgroundColor = data.homePageBottomIconBackgroundColor;
        this.footerLinks = data.footerLinks || [];
        this.menuLinks = data.menuLinks || [];
    }
}
export default new HomeModel();