module.exports = {
  //API Constant
  BASE_URL: 'https://beta.roborewards.net/api/',
  RPTOKEN: 'WMTe0jubj21PS3p4w5BFO54jE8v5Mm',
  RPID: '78b84a8c-7b9e-4c8c-82fd-3c9f9e32bf20',
  USERS: 'https://reqres.in/api/users?delay=3',
  USER_IMAGE: 'https://www.shareicon.net/data/512x512/2015/09/18/103160_man_512x512.png',
  HEADER_IMAGE: 'https://roborewards.net/UserUpload/MobileAppImages/b2cac1c9-445c-4067-bbf4-7d74d84c3dff/b1f8a177-923c-4c17-98f8-d2b5fb16f3f4.jpg?r=99980',
  GET_WEBFORMFIELD_DATA: 'UserProfile/GetFormFields',
  LOGIN: 'UserProfile/LogIn',
  FORGET_PASSWORD: 'UserProfile/ForgotPassword',
  SIGNUP: 'UserProfile/SignUp',
  GET_CONTACT_DATA: 'UserProfile/GetContactData',
  UPLOAD_PROFILE_IMAGE: 'UserProfile/ProfilePictureUpload',
  UPDATE_USER_PROFILE: 'UserProfile/UserProfileUpdate',
  CHANGE_PASSWORD: 'UserProfile/ChangePassword',
  GET_WAYTO_EARN_DATA: 'UserAccountProfile/WayToEarnScreenData',
  GET_RPG_DATA: 'UserAccountProfile/RPGScreenData',
  TRANSFERT_POINT: 'UserProfile/TransferPoints',
  GET_LOCATION_DATA: 'UserAccountProfile/GetLocationData',
  GET_CASHBACK_SCREEN_DATA: 'UserProfile/CashbackAmount',
  REDEEM_CASHBACK: 'UserProfile/CashbackRedeem',
  GET_UPLOAD_RECEIPT_SCREEN_DATA: 'UserProfile/UploadReceiptsScreenData',
  UPLOAD_RECEIPT_DATA: 'UserProfile/UploadReceipts',
  UPLOAD_RECEIPT_IMAGE: 'UserProfile/UploadReceiptsImages',
  GET_LEADERBORD_SCREEN_DATA: 'UserAccountProfile/LeaderBoardScreenData',
  GET_LEADERBOARD_FILTERED_DATA: 'UserAccountProfile/LeaderBoardReport',
  GET_OFFER_LIST: 'UserProfile/Getoffers',
  REDEEM_OFFER: 'UserProfile/RedeemOffer',
  GET_APP_INTAKEDATA: 'UserAccountProfile/AppIntakeLayoutData',
  SUBMIT_CONTACT_US: 'UserProfile/ContactUs',
  GET_TRANSACTION_HISTORY: 'UserAccountProfile/TransactionHistory',
  GET_SURVEY_LIST: 'UserAccountProfile/GetSurveyList',
  SENT_REFER_CLICK_DATA: 'UserProfile/ShareLinkVisitDetails',
  GET_ALL_BEACON:'Beacon/GetAllBeacon',
  
};
  
